name: Website
on:
  push:
    branches:
      - "main"
  pull_request: null
jobs:
  build-setup:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout the lesson
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python modules
        run: |
          python3 -m pip install --upgrade pip setuptools wheel pyyaml==5.3.1 requests
          python3 -m pip install -r requirements.txt

      - name: Setup Pandoc
        if: steps.check_files.outputs.files_exists == 'true'
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install sys deps
        run: sudo apt-get install -y libcurl4-openssl-dev

      - name: Run python build scripts
        run: |
          python bin/make_favicons.py
          python bin/get_schedules.py
          python bin/get_setup.py

      - name: Deploy the website to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: "."
          token: ${{ secrets.GITHUB_TOKEN }}
